// Validates mapping.json artifact (generated by scripts/export-mapping.ts)
// Run: npx ts-node --transpile-only --project scripts/tsconfig.json tests/validate-mapping.test.ts
// NOTE: Import from mapping.json explicitly to avoid require() collision with mapping.ts
import assert from "assert";
import { existsSync } from "fs";
import { resolve } from "path";

// Import the artifact (explicit .json path → no collision with mapping.ts)
// eslint-disable-next-line @typescript-eslint/no-require-imports
const mapping: Array<{
  topic: string;
  kind: string;
  template: string;
  pathPattern: string;
  overwrite?: boolean;
  policy?: { timestamp?: string; adrAutoSuggest?: boolean; snapshot?: boolean; clashSuffix?: boolean; requireSubtypePrompt?: boolean };
}> = require("../mapping.json");

const TEMPLATES_DIR = resolve(__dirname, "..", "templates");
const VALID_PLACEHOLDERS = new Set(["slug", "area", "type", "timestamp", "NNN"]);
let passed = 0;

function check(name: string, fn: () => void) {
  try {
    fn();
    console.log(`  ✓ ${name}`);
    passed++;
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`  ✗ ${name}: ${msg}`);
    process.exitCode = 1;
  }
}

// 1. mapping.json is a non-empty array
check("mapping.json is a non-empty array", () => {
  assert.ok(Array.isArray(mapping), "mapping.json must be an array");
  assert.ok(mapping.length > 0, "mapping.json must not be empty");
});

// 2. Unique topics
check("unique topics", () => {
  const topics = mapping.map((e) => e.topic);
  const dupes = topics.filter((t, i) => topics.indexOf(t) !== i);
  assert.strictEqual(dupes.length, 0, `Duplicate topics: ${dupes.join(", ")}`);
});

// 3. Template files exist on disk
check("all template files exist", () => {
  const missing: string[] = [];
  for (const e of mapping) {
    if (!existsSync(resolve(TEMPLATES_DIR, e.template))) {
      missing.push(`${e.topic} → ${e.template}`);
    }
  }
  assert.strictEqual(missing.length, 0, `Missing:\n  ${missing.join("\n  ")}`);
});

// 4. Only dotnet-audit-report has overwrite=true (singleton policy)
check("only singleton has overwrite=true", () => {
  const ow = mapping.filter((e) => e.overwrite === true);
  assert.strictEqual(ow.length, 1, `Expected 1 overwrite entry, got ${ow.length}: ${ow.map((e) => e.topic).join(", ")}`);
  assert.strictEqual(ow[0].topic, "dotnet-audit-report");
});

// 5. Report and plan kinds declare a timestamp policy
check("report & plan kinds have timestamp policy", () => {
  const missing = mapping.filter(
    (e) => (e.kind === "report" || e.kind === "plan") && !e.policy?.timestamp
  );
  assert.strictEqual(missing.length, 0, `Missing timestamp: ${missing.map((e) => e.topic).join(", ")}`);
});

// 6. ADR entry exists with correct policies
check("adr has adrAutoSuggest and docs/adr/ path", () => {
  const adr = mapping.find((e) => e.topic === "adr");
  assert.ok(adr, "ADR entry not found");
  assert.ok(adr!.policy?.adrAutoSuggest, "ADR missing adrAutoSuggest");
  assert.ok(adr!.pathPattern.startsWith("docs/adr/"), `Got: ${adr!.pathPattern}`);
});

// 7. No unknown placeholders in pathPatterns
check("no unknown placeholders", () => {
  const bad: string[] = [];
  const re = /\{([^}]+)\}/g;
  for (const e of mapping) {
    for (const m of e.pathPattern.matchAll(re)) {
      if (!VALID_PLACEHOLDERS.has(m[1])) bad.push(`${e.topic}: {${m[1]}}`);
    }
  }
  assert.strictEqual(bad.length, 0, `Invalid:\n  ${bad.join("\n  ")}`);
});

// 8. Short aliases brd, prd, srs present
check("short aliases brd, prd, srs exist", () => {
  for (const alias of ["brd", "prd", "srs"]) {
    const found = mapping.find((e) => e.topic === alias);
    assert.ok(found, `Alias "${alias}" not found`);
  }
});

// 9. Plan entries have clashSuffix policy
check("plan kind entries have clashSuffix policy", () => {
  const plans = mapping.filter((e) => e.kind === "plan");
  const missing = plans.filter((e) => !e.policy?.clashSuffix);
  assert.strictEqual(missing.length, 0, `Missing clashSuffix: ${missing.map((e) => e.topic).join(", ")}`);
});

console.log(`\n${passed}/9 checks passed`);
