import type { TableLocalization } from "@/types/table";

export const tableLocalizationEn: TableLocalization = {
  actions: "Actions",
  and: "and",
  cancel: "Cancel",
  clearFilter: "Clear filter",
  clearFilters: "Clear filters",
  clearSearch: "Clear search",
  clearSort: "Clear sort",
  columnActions: "Column actions",
  density: "Density",
  densityCompact: "Compact",
  densityComfortable: "Comfortable",
  densitySpacious: "Spacious",
  edit: "Edit",
  expand: "Expand",
  export: "Export",
  expandAll: "Expand all",
  filterByColumn: "Filter by {column}",
  goToFirstPage: "Go to first page",
  goToLastPage: "Go to last page",
  goToNextPage: "Go to next page",
  goToPreviousPage: "Go to previous page",
  hideAll: "Hide all",
  hideColumn: "Hide column",
  noRecordsToDisplay: "No records to display",
  noResultsFound: "No results found",
  of: "of",
  or: "or",
  page: "Page",
  pinToLeft: "Pin to left",
  pinToRight: "Pin to right",
  reset: "Reset",
  resetColumnSize: "Reset column size",
  resetOrder: "Reset order",
  rowActions: "Row actions",
  rowNumber: "#",
  rowNumbers: "Row numbers",
  rowsPerPage: "Rows per page",
  rowsSelected: "row(s) selected",
  totalItems: "{count} items total",
  pageOf: "Page {page} of {total}",
  search: "Search",
  select: "Select",
  selectAll: "Select all",
  settings: "Table settings",
  showAll: "Show all",
  showHideColumns: "Show/hide columns",
  showHideFilters: "Show/hide filters",
  showHideSearch: "Show/hide search",
  sortByColumnAsc: "Sort ascending",
  sortByColumnDesc: "Sort descending",
  toggleDensity: "Toggle density",
  toggleFullScreen: "Toggle full screen",
  toggleSelectAll: "Toggle select all",
  toggleSelectRow: "Toggle select row",
  unpin: "Unpin",
  unpinAll: "Unpin all",
};
