import type { TableLocalization } from "@/types/table";

export const tableLocalizationVi: TableLocalization = {
  actions: "Thao tác",
  and: "và",
  cancel: "Huỷ",
  clearFilter: "Xoá bộ lọc",
  clearFilters: "Xoá tất cả bộ lọc",
  clearSearch: "Xoá tìm kiếm",
  clearSort: "Bỏ sắp xếp",
  columnActions: "Thao tác cột",
  density: "Mật độ",
  densityCompact: "Gọn",
  densityComfortable: "Vừa",
  densitySpacious: "Rộng",
  edit: "Sửa",
  expand: "Mở rộng",
  expandAll: "Mở rộng tất cả",
  filterByColumn: "Lọc theo {column}",
  goToFirstPage: "Về trang đầu",
  goToLastPage: "Đến trang cuối",
  goToNextPage: "Trang sau",
  goToPreviousPage: "Trang trước",
  hideAll: "Ẩn tất cả",
  hideColumn: "Ẩn cột",
  noRecordsToDisplay: "Không có dữ liệu",
  noResultsFound: "Không tìm thấy kết quả",
  of: "trên",
  or: "hoặc",
  page: "Trang",
  pinToLeft: "Ghim trái",
  pinToRight: "Ghim phải",
  reset: "Đặt lại",
  resetColumnSize: "Đặt lại độ rộng cột",
  resetOrder: "Đặt lại thứ tự",
  rowActions: "Thao tác dòng",
  rowNumber: "STT",
  rowNumbers: "Số thứ tự",
  rowsPerPage: "Số dòng mỗi trang",
  rowsSelected: "dòng đã chọn",
  search: "Tìm kiếm",
  select: "Chọn",
  selectAll: "Chọn tất cả",
  settings: "Cấu hình bảng",
  showAll: "Hiện tất cả",
  showHideColumns: "Ẩn/hiện cột",
  showHideFilters: "Ẩn/hiện bộ lọc",
  showHideSearch: "Ẩn/hiện tìm kiếm",
  sortByColumnAsc: "Sắp xếp tăng dần",
  sortByColumnDesc: "Sắp xếp giảm dần",
  toggleDensity: "Đổi mật độ",
  toggleFullScreen: "Toàn màn hình",
  toggleSelectAll: "Chọn/bỏ chọn tất cả",
  toggleSelectRow: "Chọn/bỏ chọn dòng",
  unpin: "Bỏ ghim",
  unpinAll: "Bỏ ghim tất cả",
};
